# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
cache:
  paths:
    - build

# The YAML file defines a set of jobs with constraints stating when they should be run.
# You can specify an unlimited number of jobs which are defined as top-level elements with an arbitrary name and always have to contain at least the script clause.
# In this case we have only the test job which produce an artifacts (it must be placed into a directory called "public")
# It is also specified that only the master branch will be subject of this job.

stages:
  - build
  - test
  - badges
  - publish
  - pages

build wheel for publication: # Executed on a tag
  stage: build
  tags:
    - docker-executor
  script:
    - python setup.py egg_info -b+$CI_COMMIT_SHORT_SHA sdist bdist_wheel
  only:
    - tags
  artifacts:
    paths:
      - ./dist/

build wheel for development: # Executed on a commit
  stage: build
  tags:
    - docker-executor
  script:
    - python setup.py egg_info -b+dev.$CI_COMMIT_SHORT_SHA sdist bdist_wheel
  except:
    - tags
  artifacts:
    paths:
      - ./dist/

run tests:
  stage: test
  image: nexus.engageska-portugal.pt/ska-docker/tango-builder:latest
  before_script:
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  tags:
    - docker-executor
  script:
    - apt-get -y update
    - apt install -y jq jo bc python3-pip
    - echo $(ls -d ./dist/*.whl | grep $CI_COMMIT_SHORT_SHA)
    - pip3 install -U $(ls -d ./dist/*.whl | grep $CI_COMMIT_SHORT_SHA)
    - make test
    - scripts/validate-metadata.sh
    - echo "Saving test results into JSON format"
    - LINT_SCORE=`grep -oP 'Your code has been rated at \K.*' ./build/lmcbaseclasses_code_analysis.stdout | tail -1`
    - COVERAGE_SCORE=`awk '$1 == "TOTAL" { print $4}' ./build/lmcbaseclasses_setup_py_test.stdout | sed 's/%//g'`
    - TESTS_TOTAL=`cat ./build/lmcbaseclasses_htmlcov/report.json | jq '.summary.total'`
    - TESTS_PASSED=`cat ./build/lmcbaseclasses_htmlcov/report.json | jq '.summary.passed'`
    - jo tests_score=`bc <<< ${TESTS_PASSED}/${TESTS_TOTAL}*100` coverage_score=$COVERAGE_SCORE lint_score=`bc <<< ${LINT_SCORE}*100` > ./build/test_summary.json
  artifacts:
    paths:
      - build/test_summary.json

create badges:
  stage: badges
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  script:
    - apt-get -y update
    - apt install -y jq python3-pip
    - pip install anybadge
    - anybadge --suffix='%' -o --value=`jq '.lint_score' ./build/test_summary.json` --file=./build/lint.svg pylint
    - anybadge -o --value=`jq '.coverage_score' ./build/test_summary.json` --file=./build/coverage.svg coverage
    - anybadge --value=`jq '.tests_score' ./build/test_summary.json` --file=./build/tests.svg --label=tests coverage
  artifacts:
    paths:
      - build/lint.svg
      - build/coverage.svg
      - build/tests.svg

publish to nexus:
  stage: publish
  tags:
    - docker-executor
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    # check metadata requirements
    - scripts/validate-metadata.sh
    - pip install twine
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/*
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^.+$/ # Confirm tag message exists
      - $CI_COMMIT_TAG =~ /^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/ # Confirm semantic versioning of tag

pages:
  image: nexus.engageska-portugal.pt/ska-docker/tango-builder:latest
  before_script:
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  tags:
    - docker-executor
  stage: pages
  script:
    - mv build public
    - mv public/lmcbaseclasses_htmlcov/* public
    - make push
  artifacts:
    paths:
      - public
